use crate::address_manager::{AddressManager, AddressSet};
use common::error_location::ErrorLocation;
use common::errors::{WalletError, WalletResult};
use common::model::{
    WalletOutpoint, WalletSignableTransaction, WalletUtxo, WalletUtxoEntry,
    is_spendable_rpc_utxo_entry,
};
use itertools::Itertools;
use kaspa_consensus_core::config::params::Params;
use kaspa_rpc_core::{RpcMempoolEntryByAddress, RpcUtxosByAddressesEntry};
use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use tokio::sync::Mutex;
use tracing::warn;
use common::model::Keychain;

pub struct UtxoManager {
    address_manager: Arc<Mutex<AddressManager>>,
    coinbase_maturity: u64, // Is different in testnet

    utxos_sorted_by_amount: Vec<WalletUtxo>,
    utxos_by_outpoint: HashMap<WalletOutpoint, WalletUtxo>,
    // Since the sync stage of address collection only picks up on addresses that have accepted
    // (non-mempool) balance, we might miss some mempool outputs that are not yet accepted.
    // To mitigate this we maintain a list of mempool transactions generated by this wallet
    // that should be accepted soon, but are not yet accepted by consensus.
    mempool_transactions: Vec<WalletSignableTransaction>,
}

impl UtxoManager {
    pub fn new(address_manager: Arc<Mutex<AddressManager>>, consensus_params: Params) -> Self {
        // Upstream collapsed `coinbase_maturity` from a DAA-score-keyed
        // Forkable into a flat `u64` on the Toccata branch.
        let coinbase_maturity = consensus_params.coinbase_maturity();

        Self {
            address_manager,
            coinbase_maturity,
            utxos_sorted_by_amount: Vec::new(),
            utxos_by_outpoint: HashMap::new(),
            mempool_transactions: Vec::new(),
        }
    }

    pub fn utxos_sorted_by_amount(&self) -> Vec<WalletUtxo> {
        self.utxos_sorted_by_amount.clone()
    }

    pub fn utxos_by_outpoint(&self) -> HashMap<WalletOutpoint, WalletUtxo> {
        self.utxos_by_outpoint.clone()
    }

    pub async fn add_mempool_transaction(&mut self, transaction: &WalletSignableTransaction) {
        self.mempool_transactions.push(transaction.clone());
        self.apply_mempool_transaction(transaction).await;
    }

    async fn apply_mempool_transaction(&mut self, transaction: &WalletSignableTransaction) {
        let tx = &transaction.transaction.inner().tx;

        for input in &tx.inputs {
            let outpoint = input.previous_outpoint;
            self.remove_utxo(&outpoint.into());
        }

        for (i, output) in tx.outputs.iter().enumerate() {
            let address_string = transaction.address_by_output_index[i].to_string();
            let wallet_address = {
                let address_manager = self.address_manager.lock().await;
                address_manager
                    .wallet_address_from_string(&address_string)
                    .await
            };
            if wallet_address.is_none() {
                // this means payment is not to this wallet
                continue;
            }
            let wallet_address = wallet_address.ok_or_else(|| {
                WalletError::from(common::errors::StorageError::Io {
                    path: "mempool address".to_string(),
                    reason: "wallet address not found for mempool output".to_string(),
                    location: ErrorLocation::capture(),
                })
            })?;
            let outpoint = WalletOutpoint {
                transaction_id: tx.id(),
                index: i as u32,
            };
            // `is_unconfirmed: false` even though the parent tx has not
            // confirmed yet: this path runs only for `SubmitSource::Internal`
            // submissions whose payload we built, signed, and just shipped
            // to kaspad. The wallet retains the parent in
            // `mempool_transactions` and re-applies it after every sync via
            // `apply_mempool_transactions_after_update`, so a chained Send
            // referencing this output is safe by design. The ephemeral
            // mempool ingestion path (kaspad's `receiving` slot in
            // `update_utxo_set`) is the one that needs the unconfirmed flag.
            let utxo = WalletUtxo::new(
                outpoint.clone(),
                WalletUtxoEntry {
                    amount: output.value,
                    script_public_key: output.script_public_key.clone(),
                    block_daa_score: 0,
                    is_coinbase: false,
                    is_unconfirmed: false,
                },
                wallet_address,
            );
            self.insert_utxo(outpoint, utxo);
        }
    }

    fn insert_utxo(&mut self, outpoint: WalletOutpoint, utxo: WalletUtxo) {
        self.utxos_by_outpoint.insert(outpoint, utxo.clone());
        let position = self
            .utxos_sorted_by_amount
            .binary_search_by(|existing_utxo| {
                existing_utxo.utxo_entry.amount.cmp(&utxo.utxo_entry.amount)
            });
        let position = position.unwrap_or_else(|position| position);
        self.utxos_sorted_by_amount.insert(position, utxo);
    }

    fn contains_utxo(&self, outpoint: &WalletOutpoint) -> bool {
        self.utxos_by_outpoint.contains_key(outpoint)
    }

    fn remove_utxo(&mut self, outpoint: &WalletOutpoint) {
        if self.utxos_by_outpoint.remove(outpoint).is_none() {
            warn!("remove_utxo: outpoint {} not found in by_outpoint map", outpoint);
            return;
        }
        let position = self
            .utxos_sorted_by_amount
            .iter()
            .position(|existing_utxo| existing_utxo.outpoint.eq(outpoint));
        if let Some(pos) = position {
            self.utxos_sorted_by_amount.remove(pos);
        } else {
            warn!("remove_utxo: outpoint {} not found in sorted list", outpoint);
        }
    }

    pub async fn update_utxo_set(
        &mut self,
        rpc_utxo_entries: Vec<RpcUtxosByAddressesEntry>,
        rpc_mempool_utxo_entries: Vec<RpcMempoolEntryByAddress>,
    ) -> WalletResult<()> {
        let mut wallet_utxos: Vec<WalletUtxo> = vec![];

        let mut exclude: HashSet<WalletOutpoint> = HashSet::new();
        for rpc_mempool_entries_by_address in &rpc_mempool_utxo_entries {
            for sending_rpc_mempool_entry in &rpc_mempool_entries_by_address.sending {
                for input in &sending_rpc_mempool_entry.transaction.inputs {
                    exclude.insert(input.previous_outpoint.into());
                }
            }
        }

        let address_set: AddressSet;
        {
            let address_manager = self.address_manager.lock().await;
            address_set = address_manager.address_set().await;
        }

        for rpc_utxo_entry in &rpc_utxo_entries {
            let wallet_outpoint: WalletOutpoint = rpc_utxo_entry.outpoint.into();
            if exclude.contains(&wallet_outpoint) {
                continue;
            }

            // Covenant-bound UTXOs cannot be spent by this wallet — the
            // signer does not satisfy the covenant. Skip them at the
            // sync boundary (the only path where `RpcUtxoEntry` enters
            // the wallet) so they never reach UTXO selection.
            if !is_spendable_rpc_utxo_entry(&rpc_utxo_entry.utxo_entry) {
                warn!(
                    outpoint = ?wallet_outpoint,
                    covenant_id = ?rpc_utxo_entry.utxo_entry.covenant_id,
                    "skipping covenant-bound UTXO; this wallet cannot spend covenants"
                );
                continue;
            }

            // Safe to `try_into` after the filter above: covenant-bound
            // entries are the only failure mode and we've already skipped
            // them.
            let wallet_utxo_entry: WalletUtxoEntry = rpc_utxo_entry
                .utxo_entry
                .clone()
                .try_into()
                .map_err(|e| {
                    WalletError::from(common::errors::StorageError::Io {
                        path: "rpc_utxo_entry".to_string(),
                        reason: e.to_string(),
                        location: ErrorLocation::capture(),
                    })
                })?;

            let rpc_address = rpc_utxo_entry.address.as_ref().ok_or_else(|| {
                WalletError::from(common::errors::StorageError::Io {
                    path: "rpc_utxo_entry".to_string(),
                    reason: "address missing from RPC UTXO entry".to_string(),
                    location: ErrorLocation::capture(),
                })
            })?;
            let address = address_set.get(&rpc_address.to_string()).ok_or_else(|| {
                WalletError::from(common::errors::StorageError::Io {
                    path: rpc_address.to_string(),
                    reason: "address not found in address set".to_string(),
                    location: ErrorLocation::capture(),
                })
            })?;

            let wallet_utxo = WalletUtxo::new(wallet_outpoint, wallet_utxo_entry, address.clone());

            wallet_utxos.push(wallet_utxo);
        }

        for rpc_mempool_entry in rpc_mempool_utxo_entries {
            for receiving_rpc_mempool_entry in &rpc_mempool_entry.receiving {
                let transaction = &receiving_rpc_mempool_entry.transaction;
                let Some(transaction_verbose_data) = &transaction.verbose_data else {
                    warn!("transaction verbose data missing for mempool entry, skipping");
                    continue;
                };
                for (i, output) in transaction.outputs.iter().enumerate() {
                    let Some(output_verbose_data) = &output.verbose_data else {
                        warn!("output verbose data missing for mempool output {}, skipping", i);
                        continue;
                    };
                    let address_manager = self.address_manager.lock().await;
                    let address = address_manager
                        .wallet_address_from_string(
                            &output_verbose_data
                                .script_public_key_address
                                .address_to_string(),
                        )
                        .await;
                    if address.is_none() {
                        // this means this output is not to this wallet
                        continue;
                    }

                    let wallet_outpoint =
                        WalletOutpoint::new(transaction_verbose_data.transaction_id, i as u32);

                    if exclude.contains(&wallet_outpoint) {
                        continue;
                    }
                    // Mempool-receiving UTXOs live only in kaspad's
                    // mempool view. If kaspad evicts the parent (capacity,
                    // fee competition, re-org) before we broadcast a child,
                    // the child orphans. Tag the entry so `select_utxos`
                    // can skip it — only confirmed UTXOs are safe to spend
                    // by default. (`block_daa_score = 0` is preserved for
                    // observability; the unconfirmed bit is the load-bearing
                    // signal.)
                    let utxo_entry = WalletUtxoEntry::new(
                        output.value,
                        output.script_public_key.clone(),
                        0,
                        false,
                        true,
                    );

                    let Some(address) = address else {
                        warn!("mempool receiving address not found for output {}, skipping", i);
                        continue;
                    };
                    let utxo = WalletUtxo::new(wallet_outpoint, utxo_entry, address);

                    wallet_utxos.push(utxo);
                }
            }
        }

        self.update_utxos_sorted_by_amount(wallet_utxos.clone());
        self.update_utxos_by_outpoint(wallet_utxos);

        self.apply_mempool_transactions_after_update().await;
        Ok(())
    }

    async fn apply_mempool_transactions_after_update(&mut self) {
        let previous_mempool_transactions = std::mem::take(&mut self.mempool_transactions);
        self.mempool_transactions = vec![];
        'outer: for transaction in &previous_mempool_transactions {
            for input in transaction.transaction.inner().tx.inputs.iter() {
                let outpoint = input.previous_outpoint;
                if !self.contains_utxo(&outpoint.into()) {
                    // this means this transaction was either accepted or double-spent
                    continue 'outer;
                }
            }
            self.add_mempool_transaction(transaction).await;
        }
    }

    fn update_utxos_sorted_by_amount(&mut self, mut wallet_utxos: Vec<WalletUtxo>) {
        wallet_utxos.sort_by_key(|a| a.utxo_entry.amount);
        self.utxos_sorted_by_amount = wallet_utxos;
    }

    fn update_utxos_by_outpoint(&mut self, wallet_utxos: Vec<WalletUtxo>) {
        self.utxos_by_outpoint.clear();
        for wallet_utxo in wallet_utxos {
            self.utxos_by_outpoint
                .insert(wallet_utxo.outpoint.clone(), wallet_utxo);
        }
    }

    /// True if this UTXO must NOT be selected as a transaction input.
    ///
    /// Two unspendable shapes today:
    /// 1. `is_unconfirmed` — the UTXO came from kaspad's mempool-receiving
    ///    view. Its parent may have been evicted from kaspad's mempool by
    ///    the time we broadcast a child, producing an Orphan rejection.
    /// 2. Immature coinbase — coinbase outputs must wait
    ///    `coinbase_maturity` DAA-score units after their containing block
    ///    before consensus permits spending.
    ///
    /// Both checks default to safe-conservative (skip the UTXO). Override
    /// is intentionally not provided in this initial cut.
    pub fn is_utxo_unspendable(&self, utxo: &WalletUtxo, virtual_daa_score: u64) -> bool {
        is_utxo_unspendable_with(self.coinbase_maturity, utxo, virtual_daa_score)
    }
}

/// Pure predicate extracted for unit testing without standing up an
/// `AddressManager` + `Keys` graph just to exercise the spendability rules.
pub(crate) fn is_utxo_unspendable_with(
    coinbase_maturity: u64,
    utxo: &WalletUtxo,
    virtual_daa_score: u64,
) -> bool {
    if utxo.utxo_entry.is_unconfirmed {
        return true;
    }
    if !utxo.utxo_entry.is_coinbase {
        return false;
    }
    utxo.utxo_entry.block_daa_score + coinbase_maturity > virtual_daa_score
}

#[cfg(test)]
mod tests {
    use super::*;
    use common::model::{Keychain, WalletAddress};

    const COINBASE_MATURITY: u64 = 100;

    fn make_utxo(is_coinbase: bool, is_unconfirmed: bool, block_daa_score: u64) -> WalletUtxo {
        WalletUtxo {
            outpoint: WalletOutpoint::new(kaspa_hashes::Hash::from_bytes([1u8; 32]), 0),
            utxo_entry: WalletUtxoEntry {
                amount: 1_000,
                script_public_key: kaspa_consensus_core::tx::ScriptPublicKey::new(0, vec![].into()),
                block_daa_score,
                is_coinbase,
                is_unconfirmed,
            },
            address: WalletAddress::new(0, 0, Keychain::External),
        }
    }

    #[test]
    fn is_utxo_unspendable_rejects_unconfirmed() {
        // virtual_daa_score is irrelevant: the unconfirmed branch
        // short-circuits before the coinbase-maturity arithmetic.
        let utxo = make_utxo(false, true, 0);
        assert!(is_utxo_unspendable_with(COINBASE_MATURITY, &utxo, 999_999));
    }

    #[test]
    fn is_utxo_unspendable_accepts_normal_confirmed_utxo() {
        let utxo = make_utxo(false, false, 42);
        assert!(!is_utxo_unspendable_with(COINBASE_MATURITY, &utxo, 100));
    }

    #[test]
    fn is_utxo_unspendable_rejects_immature_coinbase() {
        // Block at score 50, coinbase_maturity = 100, virtual at 100 ⇒
        // available at score 150. Still immature.
        let utxo = make_utxo(true, false, 50);
        assert!(is_utxo_unspendable_with(COINBASE_MATURITY, &utxo, 100));
    }

    #[test]
    fn is_utxo_unspendable_accepts_mature_coinbase() {
        // Coinbase block at 50, matures at 150, virtual at 200 ⇒ mature.
        let utxo = make_utxo(true, false, 50);
        assert!(!is_utxo_unspendable_with(COINBASE_MATURITY, &utxo, 200));
    }

    #[test]
    fn is_utxo_unspendable_unconfirmed_overrides_other_checks() {
        // An unconfirmed coinbase (synthetic case) must still be rejected
        // even if it would have matured by virtual_daa_score — the mempool
        // eviction risk is the load-bearing reason, regardless of coinbase
        // maturity arithmetic.
        let utxo = make_utxo(true, true, 50);
        assert!(is_utxo_unspendable_with(COINBASE_MATURITY, &utxo, 999_999));
    }
}
