name: Docker Build Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'cli/**'
      - 'client/**'
      - 'common/**'
      - 'create/**'
      - 'daemon/**'
      - 'proto/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'Dockerfile'
      - '.github/workflows/docker-build-check.yml'

jobs:
  build-check:
    runs-on: [self-hosted, kaswallet]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
